name: Publish the extension
on: 
  push:
    branches-ignore:
      - '*'
    tags:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Publish package
        run: |
          yarn
          echo vsce publish ${GITHUB_REF##*/} -p ${{secrets.PUBLISHER_TOKEN}}